# ----------------------------
# Docker Compose file for Docker Services - Homelab Web
# Services: Cockpit
# ----------------------------
# Important: 
# Run Cockpit in Docker (complex, fragile, breaks easily) - Not recommended.
# Run Cockpit in on system is recommended.
# 

services:
# ----------------------------
# Cockpit
# ----------------------------
  cockpit:
    image: quay.io/cockpit/ws
    container_name: cockpit
    restart: unless-stopped
    privileged: true
    ports:
      - "4200:4200"
    volumes:
      - /:/host
      - /run:/run
      - /etc:/etc
      - /var:/var
      - /sys:/sys
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
