services:
  nextjs-dashboard:
    build:
      context: . # Looks for the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: nextjs_dashboard
    restart: always
    ports:
      - "8001:3000" # Host port 8001 mapped to container port 8001