services:
  nextjs_dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_dashboard
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - proxy_net
    volumes:
      - /var/lib/apt/lists:/var/lib/apt/lists:ro
      - /var/lib/dpkg/status:/var/lib/dpkg/status:ro
      - /etc/apt:/etc/apt:ro
      - /var/run/reboot-required:/var/run/reboot-required:ro
      - /var/run/reboot-required.pkgs:/var/run/reboot-required.pkgs:ro
      - /var/log/unattended-upgrades:/var/log/unattended-upgrades:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  proxy_net:
    external: true
