services:
  nextjs-dashboard:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: nextjs_dashboard
    restart: always
    ports:
      - "9000:3000"
    environment:
      - HOST=0.0.0.0 
      - PORT=3000