services:
  nextjs_dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_dashboard
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - proxy_net
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  proxy_net:
    external: true
